language: objective-c
osx_image: xcode8.3
sudo: false

env:
  global:
    - PROJECT="UINavigationItem+Margin.xcodeproj"
    - IOS_SDK="iphonesimulator10.3"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.3"
  matrix:
    - SCHEME="UINavigationItem+Margin"        SDK="$IOS_SDK"      ACTION="test"

script:
  - set -o pipefail && xcodebuild clean $ACTION -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$IOS_DESTINATION" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
